#pragma once

#define RGB_LED_R_PIN 9
#define RGB_LED_G_PIN 10
#define RGB_LED_B_PIN 11

#define BED_ROOM_LED0_PIN 3

#define LIVING_ROOM_LED0_PIN 5
#define LIVING_ROOM_LED1_PIN 6
#define LIVING_ROOM_LED2_PIN 12

#define DOOR_SERVO_PWM_PIN 4
#define WINDOW_SERVO_PWM_PIN 8

#define DOOR_OPENED_ANGLE 40
#define DOOR_CLOSED_ANGLE 105

#define WINDOW_OPENED_ANGLE 30
#define WINDOW_CLOSED_ANGLE 80